### ISSUE TITLE
link_data not linking for different plot types. 

### ISSUE THREAD

**Issue by Rmadillo** [bokeh/rbokeh#113]
Getting the error

`'link_data' was set to TRUE, but none of the figures in the grid have the same data source.`

when trying to plot histograms and scatterplots on same grid with same data source. 

Code:

```
f1 <- figure(width = 200, height = 200) %>%
    ly_hist(Sepal.Width, data = iris, freq = FALSE) %>%
    ly_density(Sepal.Width, data = iris)

f2 <- figure(width = 200, height = 200) %>%
    ly_points(Sepal.Length, Sepal.Width, data = iris,
              color = Species, glyph = Species, legend=FALSE,
              hover = list(Sepal.Length, Sepal.Width))

f3 <- figure(width = 200, height = 200) %>%
    ly_points(Petal.Width, Sepal.Width, data = iris,
              color = Species, glyph = Species, legend=FALSE,
              hover = list(Petal.Width, Sepal.Width))

f4 <- figure(width = 200, height = 200) %>%
    ly_points(Petal.Length, Sepal.Width,  data = iris,
              color = Species, glyph = Species, legend=FALSE,
              hover = list(Petal.Length, Sepal.Width))

f5 <- figure(width = 200, height = 200) %>%
    ly_points(Sepal.Width, Sepal.Length, data = iris,
              color = Species, glyph = Species, legend=FALSE,
              hover = list(Sepal.Width, Sepal.Length))

f6 <- figure(width = 200, height = 200) %>%
    ly_hist(Sepal.Length, data = iris, freq = FALSE, yname="bob") %>%
    ly_density(Sepal.Length, data = iris, yname=" ")


bob = list(f1,f2,f3,f4,f5,f6)
grid_plot(bob, ncol=4, link_data = T)
```

**Comment by hafen** [comment]
`link_data` is meant to link plots in a grid plot only when the data sources are exactly the same.  Even though you are passing the same data into the histogram plot as the other plots, it is being transformed into a different data source prior to plotting that specifies the rectangles to draw for the histogram.  So the data source for those plots is not the same and the linking cannot work.

It is R that makes the histogram binning data transformation and then the plot is sent to the browser.  At that point, the browser doesn't know anything about the transformation and therefore cannot apply it as you interactively select points on other plots.

I'm closing this since it's not an intended use case of `link_data`, but things like this will be possible with finer shiny integration and/or custom callbacks which will be added sometime soon.

**Comment by Rmadillo** [comment]
Sounds good, thanks.
