### ISSUE TITLE
in list of lists grid_plot with missing entries, axis labels may be blank

### ISSUE THREAD

**Issue by igoldin2u** [bokeh/rbokeh#184]
If you have a list-of-lists call to `grid_plot`, and if an entry in the list of lists is missing, and if that entry is the first in a row or in a column, then the axis label for that entire row or column will be blank. See the X axis label for cut==Ideal:

```
library(dplyr)
data_frame_to_lofl <- function(figs, xcol, ycol, figcol) {
  lapply(split(figs, figs[, xcol]), function(d1) {
    lapply(split(d1, d1[, ycol]), function(d2) {
      d2[, figcol][[1]][[1]]
    })
  })
}

ggplot2::diamonds %>%
  sample_frac(0.1) %>% # Too many rows in diamonds for this example
  group_by(cut, color) %>%
  filter(!(cut=="Ideal" & color=="E")) %>% # Impose data missingness
  do(fig=ly_points(figure(), x=carat, y=price, data=.)) %>%
  complete(cut, color) %>% # Back-fill a NULL entry for cut==Ideal and color==E
  data_frame_to_lofl("cut", "color", "fig") %>% # Create a list of lists
  grid_plot(same_axes=TRUE)
```

This would be fixed by only displaying each axis label once, if that's possible in Bokeh.

**Comment by hafen** [comment]
This is by design.  If a `NULL` list element is passed to `grid_plot`, it doesn't plot anything at all.  `grid_plot` tries to be agnostic to what types of plots you might put in each grid, so it doesn't try to make assumptions about what should go there if you give it an empty element.

Instead, swapping one line of your example, you can be explicit about what you want plotted in the empty grid spot (an empty figure with same plot region, etc.).

```r
ggplot2::diamonds %>%
  sample_frac(0.1) %>% # Too many rows in diamonds for this example
  group_by(cut, color) %>%
  filter(!(cut == "Ideal" & color == "E")) %>% # Impose data missingness
  complete(cut, color) %>% # Back-fill a NAs for cut==Ideal and color==E
  do(fig = ly_points(figure(), x = carat, y = price, data = .)) %>%
  data_frame_to_lofl("cut", "color", "fig") %>% # Create a list of lists
  grid_plot(same_axes = TRUE, y_margin = 100)
```

<img width="653" alt="screen shot 2016-10-05 at 5 17 24 pm" src="https://cloud.githubusercontent.com/assets/1275592/19136227/c4e3eee4-8b1f-11e6-990d-4c73ca700a7d.png">
