### ISSUE TITLE
mouse pointer misplaced in revealjs presentation

### ISSUE THREAD

**Issue by percyfal** [bokeh/rbokeh#192]
Hi,

first, kudos for creating a great package! I have been struggling to insert bokeh plots into [reveal.js](http://lab.hakim.se/reveal-js/#/) using [revealjs with rmarkdown](https://github.com/rstudio/revealjs). With rbokeh, it worked without hassle!

Well, almost. Currently, the mouse pointer is misplaced (see attached image). I am using rbokeh 0.5.0, revealjs 0.7. A minimal working example is the following markdown code:

```
---
title: "Habits"
author: John Doe
date: March 22, 2005
output: revealjs::revealjs_presentation
---

# Section 1

## Slide 1

` ``` {r, results="asis", echo=FALSE}
library(rbokeh)
p <- figure() %>%
  ly_points(Sepal.Length, Sepal.Width, data = iris,
    color = Species, glyph = Species,
    hover = list(Sepal.Length, Sepal.Width))
p
` ```
```

The command to generate the revealjs presentation is `Rscript -e "rmarkdown::render('test.Rmd')"`. I'm not quite sure how to debug this; could it be some css issue?

Cheers,

Per

![revealjs](https://cloud.githubusercontent.com/assets/739243/21142703/bb735ffc-c143-11e6-9d89-cc10cfca762d.png)

**Comment by hafen** [comment]
Hi Per,

Thanks for the kind words about the package.

This issue is being caused by revealjs using a CSS “zoom” technique on the slides that scales the plot in the browser. The mouse events are not aware of this zooming so they behave as if the image is at its original size.

You can get rid of this behavior and fix your issue by setting reveal options “minScale” and “maxScale”  to 1. I would also recommend setting figure sizes explicitly:

---
title: "Habits"
author: John Doe
date: March 22, 2005
output:
  revealjs::revealjs_presentation:
    reveal_options:
      minScale: 1
      maxScale: 1
---

# Section 1
  
## Slide 1
  
``` {r, results="asis", echo=FALSE}
library(rbokeh)
p <- figure(width = 500, height = 500) %>%
  ly_points(Sepal.Length, Sepal.Width, data = iris,
    color = Species, glyph = Species,
    hover = list(Sepal.Length, Sepal.Width))
p
```

That should solve your problem but make sure that the introduction of these parameters doesn’t effect anything else in your slides.

This raises a general question to the Bokeh development team, which is how easy would it be to make mouse events aware of any CSS zoom level that is set? It seems that as long as you are able to detect the zoom level, it would be some pretty simple math to adjust the mouse event detection, but I could be wrong. I have other use cases where this would be nice.

Ryan

**Comment by percyfal** [comment]
Hi Ryan,

that works beautifully! I guessed css was the culprit, but I had no idea where to start. Thanks for the heads up!

/P
