### ISSUE TITLE
hover does not accept a data.frame when using shiny

### ISSUE THREAD

**Issue by jrowen** [bokeh/rbokeh#82]
I think this is similar to #72.  The following app will not add hover to the chart points.
```
library(shiny)
library(rbokeh)

ui = shinyUI(fluidPage(
  sidebarLayout(
    sidebarPanel(
      selectInput("x", "X", LETTERS[1:3], "A"),
      selectInput("y", "Y", LETTERS[1:3], "B")
    ),
    mainPanel(
      rbokehOutput("plot")
    )
  )
))

server = function(input, output) {
  output$plot <- renderRbokeh({
    df_plot = data.frame(A = 1:10, B = 11:20, C = 21:30)
    
    figure() %>%
      ly_points(x = df_plot[[input$x]],
                y = df_plot[[input$y]],
                hover = df_plot)
  })
}

shinyApp(ui = ui, server = server)
```
The console states
```
hover tool not added - 'hover' must be a data frame or list of variables present in the data frame supplied as the 'data' argument
xlim not specified explicitly... calculating...
ylim not specified explicitly... calculating...
```
Everything works as expected when run outside of shiny.
```
df_plot = data.frame(A = 1:10, B = 11:20, C = 21:30)

figure() %>%
  ly_points(x = df_plot[["A"]],
            y = df_plot[["B"]],
            hover = df_plot)
```

**Comment by hafen** [comment]
I can't replicate this.  What version of rbokeh are you using?

**Comment by jrowen** [comment]
I'm using the latest dev version of bokeh/rbokeh.  I just reinstalled the dev version and am still seeing the same error (session info below).

As a test, I tried using the lazy evaluation methods from [`lazyeval`](https://github.com/hadley/lazyeval).  In particular, I changed the `hover` assignment in `ly_points` to
```
hover <- get_hover(lazyeval::lazy(hover), data)
```
and the `tmp` assignment in `get_hover` to 
```
tmp <- try(lazyeval::lazy_eval(hn), silent = TRUE)
```
and everything now works as expected in shiny.  I believe biggest difference with this approach is the calling environment is captured.  I haven't done a lot of testing with this approach but did find one problem, though
```
> figure() %>%
+   ly_points(x = A,
+             y = B,
+             data = df_plot,
+             hover = list(A, B, C))
 Error in `[.data.frame`(x, r, vars, drop = drop) : undefined columns selected 
```
My session info
```
> sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] rbokeh_0.2.3.1 shiny_0.12.1  

loaded via a namespace (and not attached):
 [1] Rcpp_0.11.6      rstudioapi_0.3.1 xml2_0.1.1      
 [4] magrittr_1.5     maps_2.3-9       devtools_1.8.0  
 [7] xtable_1.7-4     lattice_0.20-31  R6_2.0.1        
[10] stringr_1.0.0    httr_0.6.1       tools_3.2.0     
[13] grid_3.2.0       git2r_0.10.1     htmltools_0.2.6 
[16] rversions_1.0.1  yaml_2.1.13      digest_0.6.8    
[19] htmlwidgets_0.4  bitops_1.0-6     RCurl_1.95-4.6  
[22] curl_0.8         memoise_0.2.1    mime_0.3        
[25] stringi_0.4-1    jsonlite_0.9.16  httpuv_1.3.2    
[28] hexbin_1.27.0   
```

**Comment by hafen** [comment]
Aha - I just realized what I did.  I first ran your example of what does work, adding `df_plot` to my global environment.  Then I ran the app and the hover worked.

I looked into it and inside `get_hover()` in the shiny app, the data frame is 8 frames up and can't be found.  I added some logic to send the `parent.frame()` to `get_hover()` and it seems to work and seems to work for other standard cases I tested.  Would you mind taking a look at https://github.com/hafen/rbokeh/tree/fix_hover_df to see if it works for you and your use cases?

To stamp out non-standard evaluation issues for good I'm all for using lazyeval - that way we are using something that is standard and I'm sure has a lot more thought and experience behind it.  I was doing that originally but moved away because of an example like this https://github.com/hadley/lazyeval/issues/25, again having to do with environments / search path.

I'd say presuming my fix works or we can easily fix it, let's go ahead as is.

**Comment by jrowen** [comment]
Looks good and also appears to fix #72.  I agree with the approach and wouldn't advocate for switch to `lazyeval`.

**Comment by hafen** [comment]
Sounds good.  I'll test it on all the examples / web page and merge.  

BTW, I haven't forgotten about https://github.com/hafen/rbokeh/pull/2 - today has been the first somewhat normal day after multiple weeks of travel.

**Comment by hafen** [comment]
Great - tested, merged, and updated online docs.
